package edu.zju.ccnt.health.api.model.domin;

import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.Date;

/**
 * @author zth
 * @date 2019.4.24
 */

/**
 * id:主键
 * name:Api名称
 * appKey:密钥
 * address：ip:host
 * path:地址
 * httpMethod:GET:1 POST:2
 * httpProtocal:HTTP:1 HTTPS:2
 * headers:请求头,格式是 D: key:value;key:value.....
 * params:get请求携带的参数 D
 * body:post的参数 格式是 num:解释
 * num:
 * 0:Empty
 * 1:Text
 * 2:File contents
 * 3:File upload
 * description:对Api的描述
 * status:Api的状态:
 * 1:正常运行
 * 0:未上架
 * 2:已下架
 * 3:错误
 * 4:已删除
 * service_id:所属的service的主键
 * remarks:备注
 * callLimit:访问限制次数
 * callIpLimit:对单个IP的访问限制
 * resultArguments:返回的参数 D
 * errorCode 错误码 D
 * resultExample 返回示例
 * callExample 请求示例
 * createTime
 * updateTime
 */
@Data
@EqualsAndHashCode
public class Api {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.app_key
     *
     * @mbg.generated
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.http_method
     *
     * @mbg.generated
     */
    private Byte httpMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.http_protocal
     *
     * @mbg.generated
     */
    private Byte httpProtocal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.headers
     *
     * @mbg.generated
     */
    private String headers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.params
     *
     * @mbg.generated
     */
    private String params;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.body
     *
     * @mbg.generated
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.service_id
     *
     * @mbg.generated
     */
    private Integer serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.call_limit
     *
     * @mbg.generated
     */
    private Integer callLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.call_ip_limit
     *
     * @mbg.generated
     */
    private Integer callIpLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.result_arguments
     *
     * @mbg.generated
     */
    private String resultArguments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.error_code
     *
     * @mbg.generated
     */
    private String errorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.result_example
     *
     * @mbg.generated
     */
    private String resultExample;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.call_example
     *
     * @mbg.generated
     */
    private String callExample;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.id
     *
     * @return the value of api.id
     * @mbg.generated
     */

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.id
     *
     * @param id the value for api.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.name
     *
     * @return the value of api.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.name
     *
     * @param name the value for api.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.app_key
     *
     * @return the value of api.app_key
     * @mbg.generated
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.app_key
     *
     * @param appKey the value for api.app_key
     * @mbg.generated
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.address
     *
     * @return the value of api.address
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.address
     *
     * @param address the value for api.address
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.path
     *
     * @return the value of api.path
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.path
     *
     * @param path the value for api.path
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.http_method
     *
     * @return the value of api.http_method
     * @mbg.generated
     */
    public Byte getHttpMethod() {
        return httpMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.http_method
     *
     * @param httpMethod the value for api.http_method
     * @mbg.generated
     */
    public void setHttpMethod(Byte httpMethod) {
        this.httpMethod = httpMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.http_protocal
     *
     * @return the value of api.http_protocal
     * @mbg.generated
     */
    public Byte getHttpProtocal() {
        return httpProtocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.http_protocal
     *
     * @param httpProtocal the value for api.http_protocal
     * @mbg.generated
     */
    public void setHttpProtocal(Byte httpProtocal) {
        this.httpProtocal = httpProtocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.headers
     *
     * @return the value of api.headers
     * @mbg.generated
     */
    public String getHeaders() {
        return headers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.headers
     *
     * @param headers the value for api.headers
     * @mbg.generated
     */
    public void setHeaders(String headers) {
        this.headers = headers == null ? null : headers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.params
     *
     * @return the value of api.params
     * @mbg.generated
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.params
     *
     * @param params the value for api.params
     * @mbg.generated
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.body
     *
     * @return the value of api.body
     * @mbg.generated
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.body
     *
     * @param body the value for api.body
     * @mbg.generated
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.description
     *
     * @return the value of api.description
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.description
     *
     * @param description the value for api.description
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.status
     *
     * @return the value of api.status
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.status
     *
     * @param status the value for api.status
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.service_id
     *
     * @return the value of api.service_id
     * @mbg.generated
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.service_id
     *
     * @param serviceId the value for api.service_id
     * @mbg.generated
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.remarks
     *
     * @return the value of api.remarks
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.remarks
     *
     * @param remarks the value for api.remarks
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.call_limit
     *
     * @return the value of api.call_limit
     * @mbg.generated
     */
    public Integer getCallLimit() {
        return callLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.call_limit
     *
     * @param callLimit the value for api.call_limit
     * @mbg.generated
     */
    public void setCallLimit(Integer callLimit) {
        this.callLimit = callLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.call_ip_limit
     *
     * @return the value of api.call_ip_limit
     * @mbg.generated
     */
    public Integer getCallIpLimit() {
        return callIpLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.call_ip_limit
     *
     * @param callIpLimit the value for api.call_ip_limit
     * @mbg.generated
     */
    public void setCallIpLimit(Integer callIpLimit) {
        this.callIpLimit = callIpLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.result_arguments
     *
     * @return the value of api.result_arguments
     * @mbg.generated
     */
    public String getResultArguments() {
        return resultArguments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.result_arguments
     *
     * @param resultArguments the value for api.result_arguments
     * @mbg.generated
     */
    public void setResultArguments(String resultArguments) {
        this.resultArguments = resultArguments == null ? null : resultArguments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.error_code
     *
     * @return the value of api.error_code
     * @mbg.generated
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.error_code
     *
     * @param errorCode the value for api.error_code
     * @mbg.generated
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode == null ? null : errorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.result_example
     *
     * @return the value of api.result_example
     * @mbg.generated
     */
    public String getResultExample() {
        return resultExample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.result_example
     *
     * @param resultExample the value for api.result_example
     * @mbg.generated
     */
    public void setResultExample(String resultExample) {
        this.resultExample = resultExample == null ? null : resultExample.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.call_example
     *
     * @return the value of api.call_example
     * @mbg.generated
     */
    public String getCallExample() {
        return callExample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.call_example
     *
     * @param callExample the value for api.call_example
     * @mbg.generated
     */
    public void setCallExample(String callExample) {
        this.callExample = callExample == null ? null : callExample.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.create_time
     *
     * @return the value of api.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.create_time
     *
     * @param createTime the value for api.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.update_time
     *
     * @return the value of api.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.update_time
     *
     * @param updateTime the value for api.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}