package edu.zju.ccnt.health.api.dao;

import edu.zju.ccnt.health.api.model.Api;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ApiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated
     */
    int insert(Api record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated
     */
    int insertSelective(Api record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated
     */
    Api selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Api record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Api record);

    //根据服务id获取所有的api
    List<ApiBaseInfo> selectApiByServiceId(@Param("service_id") Integer service_id);
    //更新api的状态
    int updateStatus(@Param("id")Integer id,@Param("status")Integer status);

}