package edu.zju.ccnt.health.service.model;

import java.math.BigDecimal;
import java.util.Date;

public class Service {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.service_name
     *
     * @mbg.generated
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.format
     *
     * @mbg.generated
     */
    private String format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.introduction
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.detail_introduction
     *
     * @mbg.generated
     */
    private String detailIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.comment_count
     *
     * @mbg.generated
     */
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.user_count
     *
     * @mbg.generated
     */
    private Integer userCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.checked
     *
     * @mbg.generated
     */
    private Integer checked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.score
     *
     * @mbg.generated
     */
    private BigDecimal score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.is_other
     *
     * @mbg.generated
     */
    private Integer isOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.service_img
     *
     * @mbg.generated
     */
    private String serviceImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.id
     *
     * @return the value of service.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.id
     *
     * @param id the value for service.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.service_name
     *
     * @return the value of service.service_name
     * @mbg.generated
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.service_name
     *
     * @param serviceName the value for service.service_name
     * @mbg.generated
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.user_id
     *
     * @return the value of service.user_id
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.user_id
     *
     * @param userId the value for service.user_id
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.category_id
     *
     * @return the value of service.category_id
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.category_id
     *
     * @param categoryId the value for service.category_id
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.status
     *
     * @return the value of service.status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.status
     *
     * @param status the value for service.status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.price
     *
     * @return the value of service.price
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.price
     *
     * @param price the value for service.price
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.format
     *
     * @return the value of service.format
     * @mbg.generated
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.format
     *
     * @param format the value for service.format
     * @mbg.generated
     */
    public void setFormat(String format) {
        this.format = format == null ? null : format.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.introduction
     *
     * @return the value of service.introduction
     * @mbg.generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.introduction
     *
     * @param introduction the value for service.introduction
     * @mbg.generated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.detail_introduction
     *
     * @return the value of service.detail_introduction
     * @mbg.generated
     */
    public String getDetailIntroduction() {
        return detailIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.detail_introduction
     *
     * @param detailIntroduction the value for service.detail_introduction
     * @mbg.generated
     */
    public void setDetailIntroduction(String detailIntroduction) {
        this.detailIntroduction = detailIntroduction == null ? null : detailIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.comment_count
     *
     * @return the value of service.comment_count
     * @mbg.generated
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.comment_count
     *
     * @param commentCount the value for service.comment_count
     * @mbg.generated
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.user_count
     *
     * @return the value of service.user_count
     * @mbg.generated
     */
    public Integer getUserCount() {
        return userCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.user_count
     *
     * @param userCount the value for service.user_count
     * @mbg.generated
     */
    public void setUserCount(Integer userCount) {
        this.userCount = userCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.checked
     *
     * @return the value of service.checked
     * @mbg.generated
     */
    public Integer getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.checked
     *
     * @param checked the value for service.checked
     * @mbg.generated
     */
    public void setChecked(Integer checked) {
        this.checked = checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.remarks
     *
     * @return the value of service.remarks
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.remarks
     *
     * @param remarks the value for service.remarks
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.score
     *
     * @return the value of service.score
     * @mbg.generated
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.score
     *
     * @param score the value for service.score
     * @mbg.generated
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.is_other
     *
     * @return the value of service.is_other
     * @mbg.generated
     */
    public Integer getIsOther() {
        return isOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.is_other
     *
     * @param isOther the value for service.is_other
     * @mbg.generated
     */
    public void setIsOther(Integer isOther) {
        this.isOther = isOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.create_time
     *
     * @return the value of service.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.create_time
     *
     * @param createTime the value for service.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.update_time
     *
     * @return the value of service.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.update_time
     *
     * @param updateTime the value for service.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.service_img
     *
     * @return the value of service.service_img
     * @mbg.generated
     */
    public String getServiceImg() {
        return serviceImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.service_img
     *
     * @param serviceImg the value for service.service_img
     * @mbg.generated
     */
    public void setServiceImg(String serviceImg) {
        this.serviceImg = serviceImg == null ? null : serviceImg.trim();
    }
}